### ISSUE TITLE
Split structures/properties into different endpoints

### ISSUE THREAD

**Issue by muhrin** [mpds-io/mpds-api#2]
By convention REST interfaces tend to have separate endpoints for collections of similar things e.g. one endpoint for users, one for addresses, etc.  Usually the entries for each endpoint have a similar schema.

At the moment the MPDS API has the same endpoint for everything (structures and properties).  It may make things more intuitive to the user to separate these.

**Comment by blokhin** [comment]
Future API releases will support mixed content. I anyway don't like that one needs to match crystalline structures with physical property MIFs manually, this is very poor. Then *props* criterion will be optional.

**Comment by blokhin** [comment]
This is to be released in version 0.0.5

**Comment by muhrin** [comment]
Thanks Evgeny, let me know when it's released and I'll have a look.
