### ISSUE TITLE
Provide unit cell matrix when using fmt=json

### ISSUE THREAD

**Issue by muhrin** [mpds-io/mpds-api#3]
It would be useful if the JSON structure format provided the unit cell matrix as well or at least documentation of the convention for going from length/angles to the cell so that the symmetry operations are unambiguous (as typically these are relative to the method to generate the unit cell vectors from the lengths and angles).

**Comment by blokhin** [comment]
For the crystalline structures the standard settings apply, so a correct cell matrix may be obtained e.g. using **crystal** builder from *ase* (https://gitlab.com/ase/ase/blob/master/ase/spacegroup/xtal.py), implying primitive cell. For ambiguous cases, the **setting** property is available: http://developer.mpds.io/#JSON-schemata
