### ISSUE TITLE
Pauling File Mechanical Properties - Does Vickers hardness data include applied load?

### ISSUE THREAD

**Issue by sgbaird** [mpds-io/mpds-api#37]
I'm trying to figure out if the Vickers hardness data through the Pauling File contains information about load (i.e. the applied load that corresponds to the hardness measurement), or if the data is all at a fixed load, etc. Based on MPDS, I see that it has temperature data, but didn't see anything about applied load in the JSON files. I emailed Pierre from Pauling File about this and will post if I hear back.

**Comment by sgbaird** [comment]
See also https://matsci.org/t/do-you-know-of-curated-experimental-vickers-hardness-datasets-with-composition-temperature-and-load/40488

**Comment by blokhin** [comment]
These details might be available for some entries, given the original publication authors somehow highlighted them in the text of their papers. OTOH AFAIK on the large scale it's not the case.

**Comment by blokhin** [comment]
I'd recommend to check the raw Pauling File print-outs, see an icon at the left context box in the GUI. But these specific details were never systematically exposed in the machine-readable JSONs and API.

**Comment by sgbaird** [comment]
Ok, gotcha. Looking through quite a few of them (the PDF icon), I've yet to find one with the load recorded. 
![image](https://user-images.githubusercontent.com/45469701/152665935-b360649f-d398-47d2-af2c-6707084c4ffa.png)

Unfortunately, without the applied load they don't seem to have much by way of predictive potential after some initial tests with a composition-based feature vector and XGBoost.

Thanks for getting back to me on this @blokhin!

**Comment by sgbaird** [comment]
Got a response back from Pierre. He said that in the master database, there are in total about `2400` values (I assume this means entries) for hardness.

> 1500 without any remark
> 450 with remark, but no load
> 450 with load

> Conclusion: In general the load is not published, sometimes also taken from figure (no [load] given). As there exist several different hardness, like e.g. Moh's, micro, ... One can take its values (Vickers) as first approximation.
