### ISSUE TITLE
Provide discoverability mode

### ISSUE THREAD

**Issue by muhrin** [mpds-io/mpds-api#4]
Some query I can do to see what all the available, e.g., props keywords, are.

To make it more clear I'd like to be able to answer a question like: what are all the 'props' that exist for cubic, binary structures.

**Comment by blokhin** [comment]
I plan to list all the possible values of all the *q* criteria at http://datascience.mpds.io

For the case you mentioned: do you mean the functionality of the "Refinement" box? E.g. see at the left at https://mpds.io/#search/cubic%20crystalline%20structures

**Comment by blokhin** [comment]
See also https://mpds.io/sitemap
