### ISSUE TITLE
How to access bibliographic information (i.e., DOIs) for each entry?

### ISSUE THREAD

**Issue by sgbaird** [mpds-io/mpds-api#45]
I see that there is BiB information e.g. https://api.mpds.io/v0/download/p?q=P1522555-2&fmt=bib

Should I use `curl` with the endpoint above? Is this exposed in the Python client?

**Comment by blokhin** [comment]
Hi, actually this is something that was never thought to be exposed into the API i.e. for the **automated processing**. Imagine you get the bibliography information and then eventually a PDF or (especially if published until 90-es) just an article's scanned image. What do you do with it? It's absolutely not machine-readable, so only the **manual processing** is possible.

**Comment by sgbaird** [comment]
The bibliography information seems to be inaccessible now on the free version. Was this a recent change?

- https://app.screencast.com/n7QfT4bmwZ6PK

Btw, we're working through a grant proposal with a budget for MPDS access.

**Comment by blokhin** [comment]
@sgbaird OK, please let me check the status of your accounts. I‘ll write you an email then.
