### ISSUE TITLE
Can MPDSDataRetrieval (or other API access) fetch Compound Description field?

### ISSUE THREAD

**Issue by slee-lab** [mpds-io/mpds-api#52]
Hi,

I am wondering if there is any way that users can retrieve "**compound description**" field under "Experimental" which is available in the PDF but it seems I can't find a way to through the API.

1. Is this currently not allowed?
2. If not, is there a plan for implementing this feature for API access?

Thank you!

**Comment by blokhin** [comment]
That’s not available in the API as of now. If you are interested in that, please, drop me an email at support@tilde.pro CC-ing anyone who might be relevant.
