### ISSUE TITLE
Enable querying 'inside' documents

### ISSUE THREAD

**Issue by muhrin** [mpds-io/mpds-api#6]
It would be useful to be able to query something like:

`".sg_hm": "F-43m"`

To filter by entries that meet the criterion.

I realise this is a big ask and certainly a new query language should not be written.  The MongoDB one is pretty good.

**Comment by blokhin** [comment]
Hermann-Mauguin notation is supported in the existing *sgs* criterion of *q*. There are actually quite a lot of things there, but you're right, they're not "discoverable".

**Comment by blokhin** [comment]
But querying against JSON seems to be a very good idea. And you don't necessarily need a schema-less DB for that : )

**Comment by muhrin** [comment]
Yup.  I wasn't suggesting that MongoDB should be the backend, I just meant that the format of the way you express the query could be the MondoDB one, otherwise you have to make up a new one which is a huge task and would probably have problems anyway (given that MondoDB spent many years developing theirs).

**Comment by blokhin** [comment]
I see. Can you envisage more use-cases for such querying? I just had an impression that basically everything can be queried with the eight *q* properties: http://developer.mpds.io/#Categories
BTW I will present more *q* properties soon.

**Comment by blokhin** [comment]
BTW there are 13 criteria for search _q_ now.

**Comment by muhrin** [comment]
Thanks a lot Evgeny.  I'll have a look as soon as I have the chance.
