### ISSUE TITLE
Certain properties entries produce invalid JSON

### ISSUE THREAD

**Issue by muhrin** [mpds-io/mpds-api#8]
Certain queries, e.g. `{"classes": "binary", "sgs":"216", "props": "acceptor to donor concentration", "formulae":"InSb"}`

produce entries such as:
```
       {
            "sample":{
                "material":{
                ...
                },
                "measurement":[
                    {
                        "property":{
                            ...
                            "scalar":
                            }
                        }
                    ]
                },
                "version":"0.0.5"
            }
```
where the `"saralar"` field has no value.  This is invalid JSON and will result in a parser failure.

I guess there is some problem with the value in which case would it be possible to emit `null` in it's place so parsers pass?

**Comment by blokhin** [comment]
Yes, thanks, this is known and fixed in 0.0.6 (to be released in two days).
